# Generated by Django 5.1.4 on 2024-12-19 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_roommessage_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='online_users',
            field=models.ManyToManyField(blank=True, related_name='online_in_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
