# Generated by Django 5.1.4 on 2024-12-19 03:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_online_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['room_name']},
        ),
        migrations.AlterModelOptions(
            name='roommessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Room name can only contain letters, numbers, hyphens, and underscores', regex='^[a-zA-Z0-9-_]+$')]),
        ),
    ]
